### ISSUE TITLE
parameter.free() not using property 

### ISSUE THREAD

**Issue by drJfunk** [giacomov/astromodels#3]
The `<>.free()` command is trying to access a bool and not using the property setter.

So, one has to manually set `<>.free = False`

**Comment by giacomov** [comment]
I'm not sure I understand what you are saying with this. The proper way it should work is:

parameter.free = False

or equivalently:

parameter.fix = True

There isn't any free() or fix() method, so if you try to do free() you should get an error.

I've been unsure about whether to introduce free() and fix() methods instead, but in the end I think it makes sense that free is a property as are all the other things regarding a parameter, so all these statements look coeherent:

parameter.value = 1.0
parameter.delta = 0.1
parameter.min_value = -10
parameter.max_value = 10
parameter.free = True

**Comment by drJfunk** [comment]
I’m trying to free the inter calibration parameter. And when you do this it calls parameter.free() which results in an error because free is a bool.

And I’m doing this wrong?



> On Jun 9, 2016, at 9:12 AM, Giacomo Vianello <notifications@github.com> wrote:
> 
> I'm not sure I understand what you are saying with this. The proper way it should work is:
> 
> parameter.free = False
> 
> or equivalently:
> 
> parameter.fix = True
> 
> There isn't any free() or fix() method, so if you try to do free() you should get an error.
> 
> I've been unsure about whether to introduce free() and fix() methods instead, but in the end I think it makes sense that free is a property as are all the other things regarding a parameter, so all these statements look coeherent:
> 
> parameter.value = 1.0
> parameter.delta = 0.1
> parameter.min_value = -10
> parameter.max_value = 10
> parameter.free = True
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/giacomov/astromodels/issues/3#issuecomment-224817561>, or mute the thread <https://github.com/notifications/unsubscribe/AGc156L_XTGmiAjXOMBAb59I13YwWMAqks5qJ7zPgaJpZM4IuYPe>.
> 

+++++++++++++++++++++++++++++++
J Michael Burgess
+46 72-381 30 20
jmichaelburgess@gmail.com
