### ISSUE TITLE
are fits with Log_parabola broken?

### ISSUE THREAD

**Issue by sybenzvi** [giacomov/astromodels#52]
Several of us have noticed that fits to point sources with LiFF+3ML appear to be having trouble with the Log_parabola model. The fits tend to be unstable and we find that in the case where there is no curvature the model does not reduce to a simple power law. The TS is also lower for Log_parabola than for powerlaw, which should not generally occur since the extra DoF should make Log_parabola a "better" fit most of the time.

**Comment by giacomov** [comment]
This is solved now.
