### ISSUE TITLE
log parabola peak energy fix

### ISSUE THREAD

**Issue by cbrisboi** [giacomov/astromodels#63]
in astromodels/functions/functions.py
the peak energy 10**(argument) is off by a factor of ln(10). On line 1511,

>         return self.piv.value * pow(10, (2 + self.alpha.value) / (2 * self.beta.value))
should be
>         return self.piv.value * pow(10, ( (2 + self.alpha.value) * np.log(10) ) / (2 * self.beta.value))

**Comment by giacomov** [comment]
good catch! We changed a while back from log10 to log, but we didn't update the peak energy expression.
