### ISSUE TITLE
memoization and SpatialTemplate_2D

### ISSUE THREAD

**Issue by henrikef** [giacomov/astromodels#69]
Hi!

I've been tracking down a bug with `SpatialTemplate_2D` and I think I finally understand what's happening. 

`SpatialTemplate_2D` is a 2D function that reads in a map from a fits file and reports its value at a given set of coordinates. The only free parameters is a normalizing constant K, which is usually fixed to 1 if we're fitting a spectrum in 3ML.

The problem occurs if I want to have 2 or more different `SpatialTemplate_2D` functions. As the snippet  below shows, if the two `SpatialTemplate_2D` objects have the same value of the normalizing constant, their function calls will return the exact same values, even if they have different shapes according to the fits files read in. This means we cannot use 2 different `SpatialTemplate_2D` sources in astromodels/3ML at the same time.

I think this is due to memoization. If I get rid of the  `@memoize` before `Function2D._call_without_units`, it works as it should.

Is there a way to turn off memoization just for this particular function? The only way that I've come up with is to introduce a 'dummy' parameter to `SpatialTemplate_2D` which is not actually used in the function evaluation, and rely on the user to set this parameter to a unique value for each template.

[testmaps.tar.gz](https://github.com/giacomov/astromodels/files/2103403/testmaps.tar.gz)

```
from astromodels import *
from threeML import *

shape1=SpatialTemplate_2D()
shape2=SpatialTemplate_2D()

shape1.load_file("test1.fits")
shape2.load_file("test2.fits")

shape1.K = 1
shape2.K = 1

print "Using SpatialTemplate_2D.evaluate([312, 306], [41, 41], [1,1]):"
print "shape1:", shape1.evaluate( [312, 306], [41, 41], [1,1])
print "shape2:", shape2.evaluate( [312, 306], [41, 41], [1,1])

print "Using SpatialTemplate_2D function call (shape1.K = 1; shape2.K = 1):"
print "shape1:", shape1( [312, 306], [41, 41] )
print "shape2:", shape2( [312, 306], [41, 41] )

shape1.K = 1
shape2.K = 10
print "shape1.K = 1; shape2.K = 10"
print "Using SpatialTemplate_2D function call (shape1.K = 1; shape2.K = 10):"
print "shape1:", shape1( [312, 306], [41, 41] )
print "shape2:", shape2( [312, 306], [41, 41] )

shape1.K = 10
shape2.K = 10
print "Using SpatialTemplate_2D function call (shape1.K = 10; shape2.K = 10):"
print "shape1:", shape1( [312, 306], [41, 41] )
print "shape2:", shape2( [312, 306], [41, 41] )
```

output: 

```
Using SpatialTemplate_2D.evaluate([312, 306], [41, 41], [1,1]):
shape1: [1. 0.]
shape2: [0. 1.]
Using SpatialTemplate_2D function call (shape1.K = 1; shape2.K = 1):
shape1: [1. 0.]
shape2: [1. 0.]
shape1.K = 1; shape2.K = 10
Using SpatialTemplate_2D function call (shape1.K = 1; shape2.K = 10):
shape1: [1. 0.]
shape2: [ 0. 10.]
Using SpatialTemplate_2D function call (shape1.K = 10; shape2.K = 10):
shape1: [ 0. 10.]
shape2: [ 0. 10.]
```

**Comment by giacomov** [comment]
thanks for tracking this down.

The memoization can be disabled temporarily using the `use_astromodels_memoization(False)` context manager, for example:

```python
with use_astromodels_memoization(False):
    # Do something
```

However, I am not sure this is what we wanna do here, because for things like 2d templates memoization can save a huge amount of time.

One solution would be to introduce a fixed `hash` parameter and compute a hash for the content of the template file using the `hashlib` python module:

```python
hashlib.sha224(numpy_array_with_the_template).hexdigest()
```

A good place for doing this is the `_setup` method. Of course you also need to modify the `evaluate` method to accept the `hash` parameter, even though it will not do anything with it.

In this way the memoization should understand that the two templates are different.

**Comment by henrikef** [comment]
Thanks! I was looking into using a hash of the file name somehow, but I've changed it now to use the np array plus the coordinate system. Seems to be working now. I set it to calculate the hash after loading the template from a fits file in case anyone ever wants to re-use the same object with a different template.
