### ISSUE TITLE
Custom models

### ISSUE THREAD

**Issue by drJfunk** [giacomov/astromodels#7]
What is the procedure to add a custom model? If I write my own, how does astromodels import?

**Comment by giacomov** [comment]
You just need to inherit from Function1D (if it's a 1d function), and remember to use the FunctionMeta as metaclass. The metaclass will register your class among the available models.

For example, let's implement a parabolic shape:

```python
class Parabola(Function1D):
    r"""
    description :

        A parabola

    latex : $ ax^2 + bx + c $

    parameters :

        a :

            desc : a parameter
            initial value : 1
            min : -10
            max : 100

        b :

            desc : another parameter
            initial value : 2

        c:

            desc: another parameter
            initial value : 3
            fix : yes
    """

    __metaclass__ = FunctionMeta

    def _set_units(self, x_unit, y_unit):
        # a has units of y_unit / x_unit, so that a*x has units of y_unit
        self.a.unit = y_unit / x_unit**2

        # b has units of y
        self.b.unit = y_unit / x_unit

        self.c.unit = y_unit

    def evaluate(self, x, a, b, c):

        return a * x**2 + b*x + c

```

You can place this code in a notebook, in which case your function will be available only in that notebook. Or you can place it in a module anywhere in your PYTHONPATH (or the current directory) and you can import and use it.

**Comment by drJfunk** [comment]
This is wonderful. Thank you. 

/J. Michael

Sent my iPhone
