### ISSUE TITLE
linking more than two parameters

### ISSUE THREAD

**Issue by ssteinmassl** [giacomov/astromodels#72]
Hi,
is it possible to link more than two parameters in the Model.link() function at the same time other than linking them recursively? I would actually like to link 7 parameters to be linked such that they have the same value.

Cheers
Simon

**Comment by giacomov** [comment]
At the moment this is not possible. You need to loop over them, much like you would do in other software like `Xspec`.

The functionality you suggest would be useful though. If you want to submit a pull request, I'd be glad to accept it.

It is just a matter of changing this method to accept as parameter_2 a list of parameters as well as just one:

https://github.com/giacomov/astromodels/blob/17309fac8104a9a55159b1ad98b647340784d3b4/astromodels/core/model.py#L442

**Comment by grburgess** [comment]
@ssteinmassl would be cool if you can try to write this!

**Comment by ssteinmassl** [comment]
yep will do!
