### ISSUE TITLE
Parameter class docstring formatting

### ISSUE THREAD

**Issue by cdeil** [giacomov/astromodels#88]
There's a Sphinx formatting error in the Parameter class docstring:
https://astromodels.readthedocs.io/en/latest/api/astromodels.core.html#astromodels.core.parameter.Parameter

The issue seems to be that the newline in the description of the `transformation` parameter isn't handled correctly:
https://github.com/giacomov/astromodels/blob/f8741ff9386409dbf30868665a9e3186185cbcbc/astromodels/core/parameter.py#L769-L770

I'm not familiar with this docstring format, all projects I work on use the Numpy docstring standard, so I'll leave it to you.

**Comment by giacomov** [comment]
Thanks for spotting this! I fixed it.

The format of the doc is the reStructuredText format, which is the default in many tools (like for example PyCharm).

**Comment by cdeil** [comment]
Thanks!
